var teamsJson = [{"id":"100","c_name":"俄罗斯","price":0.25,"group":"A","img":"100_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Russia"},
{"id":"101","c_name":"沙特阿拉伯","price":0.25,"group":"A","img":"101_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Saudi Arabia"},
{"id":"102","c_name":"埃及","price":0.25,"group":"A","img":"102_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Saudi Arabia"},
{"id":"103","c_name":"乌拉圭","price":0.25,"group":"A","img":"103_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Uruguay"},
{"id":"104","c_name":"葡萄牙","price":0.25,"group":"B","img":"104_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Portugal"},
{"id":"105","c_name":"西班牙","price":0.25,"group":"B","img":"105_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Spain"},
{"id":"106","c_name":"摩洛哥","price":0.25,"group":"B","img":"106_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Morocco"},
{"id":"107","c_name":"伊朗","price":0.25,"group":"B","img":"107_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Iran"},
{"id":"108","c_name":"法国","price":0.25,"group":"C","img":"108_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"France"},
{"id":"109","c_name":"澳大利亚","price":0.25,"group":"C","img":"109_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Australia"},
{"id":"110","c_name":"秘鲁","price":0.25,"group":"C","img":"110_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Peru"},
{"id":"111","c_name":"丹麦","price":0.25,"group":"C","img":"111_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Denmark"},
{"id":"112","c_name":"阿根廷","price":0.25,"group":"D","img":"112_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Argentina"},
{"id":"113","c_name":"冰岛","price":0.25,"group":"D","img":"113_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Iceland"},
{"id":"114","c_name":"克罗地亚","price":0.25,"group":"D","img":"114_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Croatia"},
{"id":"115","c_name":"尼日尼亚","price":0.25,"group":"D","img":"115_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Nigeria"},
{"id":"116","c_name":"巴西","price":0.25,"group":"E","img":"116_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Brazil"},
{"id":"117","c_name":"瑞士","price":0.25,"group":"E","img":"117_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Switzerland"},
{"id":"118","c_name":"哥斯达黎加","price":0.25,"group":"E","img":"118_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"CostaRica"},
{"id":"119","c_name":"塞尔维亚","price":0.25,"group":"E","img":"119_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Serbia"},
{"id":"120","c_name":"德国","price":0.25,"group":"F","img":"120_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Germany"},
{"id":"121","c_name":"墨西哥","price":0.25,"group":"F","img":"121_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Mexico"},
{"id":"122","c_name":"瑞典","price":0.25,"group":"F","img":"122_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Sweden"},
{"id":"123","c_name":"韩国","price":0.25,"group":"F","img":"123_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Korea"},
{"id":"124","c_name":"比利时","price":0.25,"group":"G","img":"124_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Belgium"},
{"id":"125","c_name":"巴拿马","price":0.25,"group":"G","img":"125_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Panama"},
{"id":"126","c_name":"突尼斯","price":0.25,"group":"G","img":"126_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Tunisia"},
{"id":"127","c_name":"英格兰","price":0.25,"group":"G","img":"127_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"England"},
{"id":"128","c_name":"波兰","price":0.25,"group":"H","img":"128_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Poland"},
{"id":"129","c_name":"塞内加尔","price":0.25,"group":"H","img":"129_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Senegal"},
{"id":"130","c_name":"哥伦比亚","price":0.25,"group":"H","img":"130_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Columbia"},
{"id":"131","c_name":"日本","price":0.25,"group":"H","img":"131_img","firs_votes":0,"second_votes":0,"third_votes":0,"total_votes":0,"name":"Japan"}];
